### ISSUE TITLE
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by FlimzYT** [kramcat/CharacterAI#91]
Ever since the new character ai website update I cannot use this library anymore and I get this error:

Exception has occurred: JSONDecodeError
Expecting value: line 1 column 1 (char 0)
StopIteration: 0

During handling of the above exception, another exception occurred:

  File "D:\Python\Instagram Bot\main.py", line 17, in <module>
    chat = client.chat.get_chat(char)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by duyvt6663** [comment]
I think this was due to the tls fingerprint from tls_client losing to cai cloudflare. So I used a different tls fingerprint library, curl_cffi. Here is my solution:

First download the library
`pip install curl_cffi`

In **characterai.py**, add the following import 
```python
from curl_cffi import requests
```
Find and change the session initializer
```python
# self.session = tls_client.Session(
#     client_identifier='chrome112'
# ) # session using tls_client
self.session = requests.Session() # session using curl_cffi
```
Find and change the header initializer in the function **request**
```python
headers = {
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
            'Accept': 'application/json, text/plain, */*',
            'Accept-Language': 'en-US,en;q=0.5',
            'Referer': 'https://beta.character.ai',
            'Authorization': f'Token {key}',
            'Origin': 'https://beta.character.ai',
        }
```
I don't know why it works but if it works, it works

**Comment by SeoulSKY** [comment]
They started using cloudflare to fight against bots. Simple fetching won't work anymore.

**Comment by kramcat** [comment]
Fixed in the new version
