### ISSUE TITLE
Regarding to the new bot protection in character.ai

### ISSUE THREAD

**Issue by Karvp** [kramcat/CharacterAI#93]
Recently, character.ai has raised bot protection with CloudFlare to fight against bots. Now, simple fetching won't work anymore; we'll need some new approach, so I tested and found out that we have an **easy** way to play with this.

In [this line of code](https://github.com/kramcat/CharacterAI/blob/e3d6a16248ffca3ba5ad2468066d052688ff30ae/characterai/characterai.py#L20), we can simply change:
`client_identifier='chrome112'`
to
`client_identifier='firefox_120'`
(make sure you've **updated tls_client** to the [newest version](https://pypi.org/project/tls-client/))

I'm not sure what's the reason for this, but as I remember, I've read that Chrome has some tls plugins that are *harder to imitate* than Firefox's, so that's why CloudFlare can detect when you use tls_client's chrome identifier.

P/s:
I **haven't tested** it on other machines, so I'm not sure it will work well in all cases. I will keep this open for updates.

**Comment by kaiyga** [comment]
I made an unofficial little fork on codeberg that implements your idea and it seems to work

Anyone who receives a similar #90 #91  error can try using it instead of the original library.
Replace in requrements `characterai` to ` git+https://codeberg.org/kaiyga/CharacterAITestfork.git@main#egg=characterai ` 

This is a temporary solution, it is not correct, it is not safe. I just implemented the idea above
Wait official commit, official solution!

**Comment by Karvp** [comment]
Just a little note that it isn't that dangerous. Changing the identifier won't affect anything except making your requests **look like** from a Firefox client.

**Comment by O-Braixen** [comment]
I'm trying to host my version on square cloud but I can't because of the same error generated, I tried to implement CharacterAITestfork but without success, in my case I use chat2 from PyAsyncCAI

**Comment by kramcat** [comment]
Fixed in the new version
